-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 21:07:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sistema_resilia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_resilia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_resilia` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `sistema_resilia`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_resilia`.`alunos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `curso` VARCHAR(45) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `telefone` VARCHAR(12) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistema_resilia`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_resilia`.`disciplina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(15) NULL DEFAULT NULL,
  `carga_horaria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistema_resilia`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_resilia`.`curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL DEFAULT NULL,
  `carga_horaia` INT(11) NULL DEFAULT NULL,
  `disciplina_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_curso_disciplina_idx` (`disciplina_id` ASC),
  CONSTRAINT `fk_curso_disciplina`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `sistema_resilia`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`MATRICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MATRICULA` (
  `data_matricula` INT NULL,
  `alunos_id` INT(11) NOT NULL,
  `curso_id` INT(11) NOT NULL,
  INDEX `fk_MATRICULA_alunos_idx` (`alunos_id` ASC),
  INDEX `fk_MATRICULA_curso1_idx` (`curso_id` ASC),
  CONSTRAINT `fk_MATRICULA_alunos`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `sistema_resilia`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULA_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sistema_resilia`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sistema_resilia` ;

-- -----------------------------------------------------
-- Table `sistema_resilia`.`co_facilitador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_resilia`.`co_facilitador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `telefone` VARCHAR(12) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistema_resilia`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_resilia`.`turma` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_turma` INT(11) NULL DEFAULT NULL,
  `alunos_id` INT(11) NOT NULL,
  `co_facilitador_id` INT(11) NOT NULL,
  `disciplina_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_alunos1_idx` (`alunos_id` ASC),
  INDEX `fk_turma_co_facilitador1_idx` (`co_facilitador_id` ASC),
  INDEX `fk_turma_disciplina1_idx` (`disciplina_id` ASC),
  CONSTRAINT `fk_turma_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `sistema_resilia`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_co_facilitador1`
    FOREIGN KEY (`co_facilitador_id`)
    REFERENCES `sistema_resilia`.`co_facilitador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `sistema_resilia`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
